### ISSUE TITLE
TypeError: Cannot destructure property 'accessToken' of 'res.body' as it is undefined.

### ISSUE THREAD

**Issue by Flamtky** [SmartCity-2022/Service-Buergerbuero#23]
TypeError: Cannot destructure property 'accessToken' of 'res.body' as it is undefined.
at /app/middlewares/auth.js:40:25
at processTicksAndRejections (node:internal/process/task_queues:96:5)
at async auth (/app/middlewares/auth.js:35:9)

**Comment by shakerrrr** [comment]
ja da ist dann beim mainhub irgendwas scuffed weil ich erwarte da nen accessToken so wie das bei denen im code beschrieben ist 
`app.post('/api/token', (req, res) => {
    const refreshToken = req.body.token
    if(refreshToken == null) return res.status(401).send({errMsg:  constants.ERR_MISSING_TOKEN})
    if(!refreshTokens.includes(refreshToken)) return res.status(403).send({errMsg: constants.ERR_INVALID_TOKEN})
    jwt.verify(refreshToken, process.env.REFRESH_TOKEN_SECRET, (err, user) => {
        if(err) return res.status(403).send({errMsg: constants.ERR_INVALID_TOKEN})
        const accessToken = generateAccessToken({ name: user.name })
        return res.json({ accessToken: accessToken })
    })
})`
aber vielleicht hab ich auch was übersehen aber glaube nicht.
die wollen da ja den refresh token im request als "token" haben was ich auch so abschicke und die wollen da dann ja nen "accessToken" zurück schicken und ich fange den auf aber da kommt laut der fehlermeldung wohl nix an.

ich gucke gleich mal, dass ich da den fehler ausgeben wenn ich kein accessToken von denen zurück bekomme

**Comment by shakerrrr** [comment]
hoffe mal das hat daran gelegen, dass ich zwei "res" hatte. wenn nicht hab ich keine ahnung was falsch ist
